# Generated by Django 3.0.3 on 2020-04-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200409_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostDesc',
        ),
    ]
