# Generated by Django 3.0.3 on 2020-04-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.TextField(default='Genre:Action,Drama,Comedy'),
            preserve_default=False,
        ),
    ]
