# Generated by Django 3.0.3 on 2020-04-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_list', models.IntegerField()),
                ('op_list', models.TextField()),
                ('ed_list', models.TextField()),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
